const Items = [
    {
        id: '001',
        image: 'picture/1.jpg',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        current_price: 606,
        price: 1045,
        off: 42,
        deliver_time: '14 days return available',
        delivery_date: '26 March 2025',
    },
    {
        id: '002',
        image: 'picture/2.jpg',
        company: 'CUKOO',
        item_name: 'Women Padded Halter Neck Swimming Dress',
        current_price: 1507,
        price: 2599,
        off: 42,
        deliver_time: '14 days return available',
        delivery_date: '26 March 2025',
    },
    {
        id: '003',
        image: 'picture/3.jpg',
        company: 'NUEVOSDAMAS',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        current_price: 495,
        price: 1599,
        off: 69,
        deliver_time: '14 days return available',
        delivery_date: '26 March 2025',
    },
    {
        id: '004', // Fixed duplicate id
        image: 'picture/5.jpg',
        company: 'ADIDAS',
        item_name: 'Indian Cricket ODI Jersey',
        current_price: 999,
        price: 999,
        off: 0,
        deliver_time: '14 days return available',
        delivery_date: '26 March 2025',
    },
    {
        id: '005',
        image: 'picture/6.jpg',
        company: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        current_price: 489,
        price: 1399,
        off: 65,
        deliver_time: '14 days return available',
        delivery_date: '26 March 2025',
    },
    {
        id: '006',
        image: 'picture/7.jpg',
        company: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        current_price: 14995,
        price: 14995,
        off: 0,
        deliver_time: '14 days return available',
        delivery_date: '26 March 2025',
    },
    {
        id: '007',
        image: 'picture/8.jpg',
        company: 'The Indian Garage Co',
        item_name: 'Men Slim Fit Regular Shorts',
        current_price: 639,
        price: 1599,
        off: 60,
        deliver_time: '14 days return available',
        delivery_date: '26 March 2025',
    },
    {
        id: '008',
        image: 'picture/greeen t-shirt.jpg',
        company: 'Nivea',
        item_name: 'Men Fresh Deodorant 150ml',
        current_price: 142,
        price: 285,
        off: 50,
        deliver_time: '14 days return available',
        delivery_date: '26 March 2025',
    }
];
