
const items = [
    {
        id: '001',
        image: 'images/1.jpg',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        current_price: 1045,
        price: 606,
        off: '42%',
        addcartButton: 'Add to Cart',
    },
    {
        id: '002',
        image: 'images/2.jpg',
        company: 'CUKOO',
        item_name: 'Women Padded Halter Neck Swimming Dress',
        current_price: 2599,
        price: 1507,
        off: '42%',
        addcartButton: 'Add to Cart',
    },
    {
        id: '003',
        image: 'images/3.jpg',
        company: 'NUEVOSDAMAS',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        current_price: 1599,
        price: 495,
        off: '69%',
        addcartButton: 'Add to Cart',
    },
    {
        id: '005',
        image: 'images/5.jpg',
        company: 'ADIDAS',
        item_name: 'Indian Cricket ODI Jersey',
        current_price: 999,
        price: 999,
        off: '0%',
        addcartButton: 'Add to Cart',
    },
    {
        id: '006',
        image: 'images/6.jpg',
        company: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        current_price: 1399,
        price: 489,
        off: '65%',
        addcartButton: 'Add to Cart',
    },
    {
        id: '007',
        image: 'images/7.jpg',
        company: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        current_price: 14995,
        price: 14995,
        off: '0%',
        addcartButton: 'Add to Cart',
    },
    {
        id: '008',
        image: 'images/8.jpg',
        company: 'The Indian Garage Co',
        item_name: 'Men Slim Fit Regular Shorts',
        current_price: 1599,
        price: 639,
        off: '60%',
        addcartButton: 'Add to Cart',
    },
    {
        id: '008',
        image: 'images/greeen t-shirt.jpg', // Fixed image path
        company: 'Nivea',
        item_name: 'Men Fresh Deodorant 150ml',
        current_price: 285,
        price: 142,
        off: '50%',
        addcartButton: 'Add to Cart',
    }
];
    